# Alacritty Configuration - idleToes Theme

[colors.primary]
# Alternate backgrounds to try:
# background = "#36393f" # pretty light, a little too light
# background = "#343639" # roughly halfway between the above and below...
# background = "#323232" # neutral darkish grey
background = "#313336"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#d6d6d6"

[cursor.style]
shape = "Beam"
blinking = "On"

[colors.normal]
black   = "#191b1d"
red     = "#db7771"
green   = "#7fd276"
yellow  = "#ffc252"
blue    = "#51a2f8"
magenta = "#d082dc"
cyan    = "#00d7e0"
white   = "#cfd1d4"

[colors.bright]
black   = "#6c6f73"
red     = "#ffaba3"
green   = "#b2fbaa"
yellow  = "#ffeebb"
blue    = "#8dc2fe"
magenta = "#f5b8fe"
cyan    = "#57f5f5"
white   = "#ffffff"

[font]
size = 8.0

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[window]
dynamic_padding = true

[general]
import = [
    "~/.dotfiles/config/alacritty/extended-keys.toml"
]
