#!/bin/env -S zsh -euo pipefail

function up {
  arrange DP3 DP4
  sleep 1

  printf '(xrandr)» repositioning eDP1 centered below LG5k...\n'
  xrandr --output eDP1 --pos 640x2880

  bspwm_reset

  printf 'resetting wallpaper(s)...\n'
  ~/.feh-set-background

  printf 'ok! LG5k up.\n'
}

function arrange {
  printf '(xrandr)» combining %s, %s into one LG5k 5120x2880...\n' ${1} ${2}
  xrandr --setmonitor LG5k 5120/600x2880/340+0+0 ${1},${2}

  printf '(xrandr)» arranging %s left and %s right...\n' ${1} ${2}
  xrandr --output ${1} --mode 2560x2880 --pos 0x0
  xrandr --output ${2} --mode 2560x2880 --pos 2560x0

  printf 'ok! arranged virtual monitors.\n'
}

function bspwm_reset {
  printf '(bspc)» removing DP3, DP4, and LG5k from bspwm...\n'
  while bspc monitor DP3 --remove; do; done &>/dev/null
  while bspc monitor DP4 --remove; do; done &>/dev/null
  while bspc monitor LG5k --remove; do; done &>/dev/null

  sleep 1
  printf '(bspc)» adding LG5k to bspwm...\n'
  bspc wm --add-monitor LG5k 5120x2880+0+0

  sleep 1
  printf '(bspc)» resetting desktops across LG5k and eDP1...\n'
  bspc wm --reorder-monitors LG5k eDP1
  bspc monitor LG5k --reset-desktops I II III
  bspc monitor eDP1 --reset-desktops IV V VI

  bspc wm --adopt-orphans
}

function down {
  printf '(xrandr)» deleting LG5k from xRandR and powering it off...\n'
  xrandr --delmonitor LG5k
  xrandr --output DP3 --off
  xrandr --output DP4 --off

  printf '(bspc)» removing LG5k from bspwm...\n'
  bspc monitor LG5k --remove
  printf '(bspc)» resetting desktops...\n'
  bspc monitor eDP1 --reset-desktops I II III IV V VI
  printf '(bspc)» adopting orphans to focused monitor...\n'
  bspc wm --adopt-orphans

  printf 'ok! LG5k down.\n'
}

cmd=${1}
shift

${cmd} ${@} || echo "usage: $0 up|down"
