color0 #323232
color1 #d25252
color2 #7fe173
color3 #ffc66d
color4 #4099ff
color5 #f680ff
color6 #bed6ff
color7 #eeeeec
color8 #535353
color9 #f07070
color10 #9dff91
color11 #ffe48b
color12 #5eb7f7
color13 #ff9dff
color14 #dcf4ff
color15 #ffffff
background #36393f
selection_foreground #323232
cursor #d6d6d6
foreground #ffffff
selection_background #ffffff


#    uno_1        #d6e9ff
#    uno_2        #abb2bf
#    uno_3        #6e88a6
#    uno_4        #55606d
#
#    duo_1        #c8ae9d
#    duo_2        #e06c75
#    duo_3        #dd672c
#
#    renamed      #33a0ff
#    added        #43d08a
#    modified     #e0c285
#    removed      #e05252
#
#    fg           s:uno_2
#    bg           #282c34
#    accent       #56b6c2
#    gutter       #636d83
#    selection    #3e4452
#    rule_fg      #5c6370
#    fold_bg      #333943
#    cursor_line  #2c323c
